# Generated by Django 5.2.1 on 2025-06-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LessonSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="タイトル")),
                ("start_time", models.DateTimeField(verbose_name="開始日時")),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="終了日時 (任意)"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="説明"),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        max_length=7,
                        null=True,
                        verbose_name="カレンダーの色",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "授業予定",
                "verbose_name_plural": "授業予定",
                "ordering": ["start_time"],
            },
        ),
    ]
