# Generated by Django 5.2.1 on 2025-06-11 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutor", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Homework",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="課題名")),
                ("due_date", models.DateField(verbose_name="提出期限")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "未提出"),
                            ("submitted", "提出済み"),
                            ("completed", "完了"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="homework_attachments/",
                        verbose_name="課題添付ファイル",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_homeworks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者(講師)",
                    ),
                ),
            ],
            options={
                "verbose_name": "課題",
                "verbose_name_plural": "課題",
                "ordering": ["due_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField(verbose_name="問題文")),
                (
                    "question_type",
                    models.CharField(
                        choices=[("text", "文章解答"), ("choice", "選択肢")],
                        max_length=20,
                        verbose_name="問題形式",
                    ),
                ),
                (
                    "choices",
                    models.JSONField(
                        blank=True, null=True, verbose_name="選択肢 (選択肢形式の場合)"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="表示順序")),
                (
                    "homework",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="tutor.homework",
                        verbose_name="関連課題",
                    ),
                ),
            ],
            options={
                "verbose_name": "問題",
                "verbose_name_plural": "問題",
                "ordering": ["homework", "order"],
            },
        ),
        migrations.CreateModel(
            name="StudentHomeworkSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="提出日時"),
                ),
                (
                    "student_attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="student_submissions/",
                        verbose_name="生徒提出ファイル",
                    ),
                ),
                (
                    "is_graded",
                    models.BooleanField(default=False, verbose_name="採点済み"),
                ),
                (
                    "homework",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="tutor.homework",
                        verbose_name="提出課題",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submitted_homeworks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="提出生徒",
                    ),
                ),
            ],
            options={
                "verbose_name": "生徒課題提出",
                "verbose_name_plural": "生徒課題提出",
                "ordering": ["-submitted_at"],
                "unique_together": {("homework", "student")},
            },
        ),
        migrations.CreateModel(
            name="TutorGrading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="点数/評価"
                    ),
                ),
                (
                    "feedback",
                    models.TextField(
                        blank=True, null=True, verbose_name="フィードバック"
                    ),
                ),
                (
                    "graded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="採点日時"),
                ),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grading",
                        to="tutor.studenthomeworksubmission",
                        verbose_name="関連提出",
                    ),
                ),
                (
                    "tutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="graded_submissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="採点者(講師)",
                    ),
                ),
            ],
            options={
                "verbose_name": "講師採点",
                "verbose_name_plural": "講師採点",
            },
        ),
        migrations.CreateModel(
            name="StudentAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text_answer",
                    models.TextField(blank=True, null=True, verbose_name="文章解答"),
                ),
                (
                    "selected_choice_index",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="選択肢インデックス"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_answers",
                        to="tutor.question",
                        verbose_name="関連問題",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="tutor.studenthomeworksubmission",
                        verbose_name="関連提出",
                    ),
                ),
            ],
            options={
                "verbose_name": "生徒解答",
                "verbose_name_plural": "生徒解答",
                "unique_together": {("submission", "question")},
            },
        ),
    ]
