# Generated by Django 5.2.1 on 2025-06-11 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutor", "0002_homework_question_studenthomeworksubmission_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="studenthomeworksubmission",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="homework",
            name="tutor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_homeworks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="作成者(講師)",
            ),
        ),
        migrations.AlterField(
            model_name="studenthomeworksubmission",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submitted_homeworks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="提出生徒",
            ),
        ),
        migrations.AlterField(
            model_name="tutorgrading",
            name="tutor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="graded_submissions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="採点者(講師)",
            ),
        ),
    ]
